// create some array of object date here 
const bioBlodDonner = [{
        id: 1,
        name: "Asrafull",
        age: 26,
        bloodGroup: "A",
        address: "Mirpur",
        phone: "016432735",
        lastDonad: 90,
        isMarriage: false,
    },
    {
        id: 2,
        name: "Nurjamall",
        age: 37,
        bloodGroup: "A+",
        address: "Dinajpur",
        phone: "016432735",
        lastDonad: 60,
        isMarriage: true,
    },
    {
        id: 3,
        name: "Asutos gosh",
        age: 30,
        bloodGroup: "AB+",
        address: "Uttara",
        phone: "016432735",
        lastDonad: 120,
        isMarriage: false,
    },
    {
        id: 4,
        name: "Mahdi",
        age: 45,
        bloodGroup: "AB-",
        address: "Mirpur",
        phone: "016432735",
        lastDonad: 90,
        isMarriage: true,
    },
    {
        id: 5,
        name: "Uttam Roy",
        age: 40,
        bloodGroup: "A+",
        address: "Kuyakata",
        phone: "016432735",
        lastDonad: 100,
        isMarriage: false,
    },
    {
        id: 6,
        name: "Jamal",
        age: 60,
        bloodGroup: "O-",
        address: "Uttara",
        phone: "016432735",
        lastDonad: 80,
        isMarriage: false,
    },
    {
        id: 7,
        name: "Raja",
        age: 30,
        bloodGroup: "O+",
        address: "Rangpur",
        phone: "016432735",
        lastDonad: 120,
        isMarriage: false,
    },
]